In [1]:
cd ..

/home/jovyan/bg_recommender


In [2]:
import numpy as np
import psycopg2 as pg2
from psycopg2.extras import RealDictCursor


In [3]:
%run lib/helper/load_rec_mats.py

In [4]:
whos

Variable         Type              Data/Info
--------------------------------------------
RealDictCursor   type              <class 'psycopg2.extras.RealDictCursor'>
exp_mat          ndarray           10000x10000: 100000000 elems, type `float64`, 800000000 bytes (762.939453125 Mb)
f                BufferedReader    <_io.BufferedReader name='data/item_bias'>
feat_mat         ndarray           10000x10000: 100000000 elems, type `float64`, 800000000 bytes (762.939453125 Mb)
item_bias        ndarray           10000: 10000 elems, type `float64`, 80000 bytes
item_mat         ndarray           10000x10000: 100000000 elems, type `float64`, 800000000 bytes (762.939453125 Mb)
np               module            <module 'numpy' from '/op<...>kages/numpy/__init__.py'>
pg2              module            <module 'psycopg2' from '<...>es/psycopg2/__init__.py'>
pickle           module            <module 'pickle' from '/o<...>lib/python3.6/pickle.py'>


In [10]:
comb_mat = np.add(np.multiply(feat_mat, .3), np.multiply(item_mat, .7))

In [47]:
def con_cur_to_bgg_db():
    con = pg2.connect(host='34.216.22.202',
                  dbname='postgres',
                  user='postgres')
    cur = con.cursor(cursor_factory=RealDictCursor)
    return con, cur

def insert_sim(sim_mat):
    con, cur = con_cur_to_bgg_db()
    for i in range(10000):
        cur.execute("INSERT INTO rec_lookup (gs, sim) VALUES\
                ({}, '{{{}}}');".format(i, str(list(sim_mat[i]))[1:-1]))
    con.commit()
    con.close()
    
def insert_top_K(top_K_mat):
    con, cur = con_cur_to_bgg_db()
    for i in range(10000):
        cur.execute("UPDATE rec_lookup SET top_k = \
                '{{{}}}' WHERE gs={};".format(str(list(top_K_mat[i]))[1:-1], i))
    con.commit()
    con.close()
    
def insert_exp(exp_dict):
    con, cur = con_cur_to_bgg_db()
    for i in range(10000):
        if exp_dict[i]:
            cur.execute("UPDATE rec_lookup SET exp = \
                '{{{}}}' WHERE gs={};".format(str(list(exp_dict[i]))[1:-1], i))
    con.commit()
    con.close()
    

In [45]:
str(list(exp_dict[0]))[1:-1]

'117, 136, 157, 498, 691, 734, 749, 936, 1071, 1212, 1622, 1828, 2099, 2186, 2262, 2321, 2394, 2538, 2970, 3236, 3293, 3465, 3664, 4545, 5501, 5665, 5819, 7273, 7355, 8273, 8315, 9210, 9643, 9766'

In [46]:
exp_dict[0]

[117,
 136,
 157,
 498,
 691,
 734,
 749,
 936,
 1071,
 1212,
 1622,
 1828,
 2099,
 2186,
 2262,
 2321,
 2394,
 2538,
 2970,
 3236,
 3293,
 3465,
 3664,
 4545,
 5501,
 5665,
 5819,
 7273,
 7355,
 8273,
 8315,
 9210,
 9643,
 9766]

In [84]:
insert_sim(comb_mat)

In [50]:
con, cur = con_cur_to_bgg_db()
cur.execute("SELECT * FROM rec_lookup LIMIT 1;")
foo = cur.fetchall()
con.close()

In [51]:
foo

[{'exp': [186, 288, 595, 910, 1221, 1343, 9090],
  'gs': 4,
  'sim': [0.277570779113558,
   0.25976136839161,
   0.344434709011871,
   0.37702687756766,
   0.999931700653722,
   0.362592629783426,
   0.289586634563222,
   0.271112178548422,
   0.296546559235561,
   0.202470230282873,
   0.242464200890809,
   0.396555300186559,
   0.28276226559983,
   0.383325148870883,
   0.365107972021415,
   0.174645515735962,
   0.383634579362461,
   0.228380836371885,
   0.365620811442369,
   0.365380092968662,
   0.189540657341725,
   0.266638377396825,
   0.285600432522665,
   0.31431447084362,
   0.175552705652296,
   0.324325872859496,
   0.281376601094804,
   0.16087180630064,
   0.181802542335123,
   0.255719430896664,
   0.240040859975683,
   0.545866433900378,
   0.21995443688693,
   0.161979133547679,
   0.179929324522369,
   0.381750517438459,
   0.198934149398661,
   0.189652073177448,
   0.201757002444225,
   0.223236741165288,
   0.405301628502552,
   0.260449450661527,
   0.1662120656

In [35]:
noz = exp_mat.nonzero()

In [36]:
list(zip(noz[0], noz[1]))

[(0, 117),
 (0, 136),
 (0, 157),
 (0, 498),
 (0, 691),
 (0, 734),
 (0, 749),
 (0, 936),
 (0, 1071),
 (0, 1212),
 (0, 1622),
 (0, 1828),
 (0, 2099),
 (0, 2186),
 (0, 2262),
 (0, 2321),
 (0, 2394),
 (0, 2538),
 (0, 2970),
 (0, 3236),
 (0, 3293),
 (0, 3465),
 (0, 3664),
 (0, 4545),
 (0, 5501),
 (0, 5665),
 (0, 5819),
 (0, 7273),
 (0, 7355),
 (0, 8273),
 (0, 8315),
 (0, 9210),
 (0, 9643),
 (0, 9766),
 (1, 84),
 (1, 128),
 (1, 202),
 (1, 235),
 (1, 297),
 (1, 327),
 (1, 517),
 (1, 580),
 (1, 590),
 (1, 618),
 (1, 628),
 (1, 764),
 (1, 1056),
 (1, 1057),
 (1, 1144),
 (1, 1161),
 (1, 1207),
 (1, 1554),
 (1, 1783),
 (1, 1792),
 (1, 1799),
 (1, 1905),
 (1, 1935),
 (1, 2003),
 (1, 2234),
 (1, 2308),
 (1, 2315),
 (1, 2333),
 (1, 2387),
 (1, 2396),
 (1, 2434),
 (1, 2709),
 (1, 2728),
 (1, 3061),
 (1, 3249),
 (1, 3341),
 (1, 3912),
 (1, 4936),
 (1, 4962),
 (1, 4971),
 (1, 5524),
 (1, 5692),
 (1, 5932),
 (1, 6506),
 (1, 7142),
 (1, 7157),
 (1, 7773),
 (1, 8095),
 (1, 9986),
 (2, 44),
 (2, 123),
 (2,

In [30]:
exp_dict = {}

In [31]:
for i in range(10000):
    exp_dict[i] = []

In [37]:
for gs, exp in zip(noz[0], noz[1]):
    exp_dict[gs].append(exp)

In [48]:
insert_exp(exp_dict)

In [49]:
with open('data/exp_dict', 'wb') as f:
    pickle.dump(exp_dict, f)

In [42]:
repr(exp_dict[0])

'[117, 136, 157, 498, 691, 734, 749, 936, 1071, 1212, 1622, 1828, 2099, 2186, 2262, 2321, 2394, 2538, 2970, 3236, 3293, 3465, 3664, 4545, 5501, 5665, 5819, 7273, 7355, 8273, 8315, 9210, 9643, 9766]'

In [6]:
no_exp_item_mat = item_mat.copy()

In [7]:
no_exp_item_mat[exp_mat.nonzero()] = 0

In [97]:
no_exp_feat_mat = feat_mat.copy()

In [98]:
no_exp_feat_mat[exp_mat.nonzero()] = 0

In [99]:
sum(no_exp_feat_mat == 0)

array([41, 56, 15, ...,  9,  8,  8])

In [154]:
feat_sim_sorted = np.argsort(no_exp_feat_mat, axis=1)

MemoryError: 

In [126]:
feat_sim_50 = np.array([feat_sim_sorted[i][-2:-52:-1] for i in range(10000)])

In [5]:
import pickle

In [165]:
with open('data/feat_sim_50', 'wb') as f:
    pickle.dump(feat_sim_50, f)

In [8]:
with open('data/feat_sim_50', 'rb') as f:
    feat_sim_50 = pickle.load(f)

In [9]:
for i in range(10000):
    no_exp_item_mat[i][feat_sim_50[i]] = 0

In [170]:
del feat_sim_50

In [139]:
np.argsort(no_exp_item_mat[0])[-2:-52:-1]

array([5247, 7207, 9278, 8924, 8187, 9709, 7941, 7920, 8526, 8060, 9073,
       9443, 7365, 9141, 6328, 8996, 7844, 5503, 5505, 8862, 7311, 5315,
       8907, 3266, 8995, 7062, 7109, 7660, 9414, 5453, 7746, 9193, 9348,
       9513, 9924, 8737, 8736, 9182, 9563, 8690, 9436, 4934, 8396, 6792,
       8619, 9319, 8508, 9874, 7696, 8606])

In [153]:
no_exp_item_mat.shape

(10000, 10000)

In [10]:
with open('data/no_exp_no_feat_item_mat', 'wb') as f:
    pickle.dump(no_exp_item_mat, f)

In [11]:
item_sim_sorted = np.argsort(no_exp_item_mat, axis=1)

In [13]:
item_sim_sorted[0][-1:-5:-1]

array([   0, 5247, 7207, 9278])

In [14]:
item_sim_50 = np.array([item_sim_sorted[i][-2:-52:-1] for i in range(10000)])

In [17]:
sim_100 = np.concatenate((feat_sim_50, item_sim_50), axis=1)

In [19]:
with open('data/sim_100', 'wb') as f:
    pickle.dump(sim_100, f)

In [25]:
insert_top_K(sim_100)

In [15]:
item_sim_50.shape

(10000, 50)

In [189]:
whos

Variable          Type       Data/Info
--------------------------------------
no_exp_item_mat   ndarray    10000x10000: 100000000 elems, type `float64`, 800000000 bytes (762.939453125 Mb)
np                module     <module 'numpy' from '/op<...>kages/numpy/__init__.py'>
pickle            module     <module 'pickle' from '/o<...>lib/python3.6/pickle.py'>


In [188]:
del con_cur_to_bgg_db

In [148]:
del sim_list

In [149]:
del str_list