In [4]:
import numpy as np

In [2]:
cd ..

/home/jovyan


In [3]:
from lib.helper import sizeof

In [12]:
row = np.random.randint(1, 10, 10000)

In [13]:
test = {}
for i in range(10000):
    test[i] = row

In [41]:
sim = np.random.randint(0, 9999, 50)

In [50]:
foo = [(np.random.randint(0, 9999, 50), np.random.randint(0, 9999, 50), np.random.rand(10000), np.random.rand(10000)) for x in range(7)]

In [51]:
type(foo[0])

tuple

In [86]:
foo

[(array([3513, 7990, 6040, 3484, 8808, 4439, 5472, 6627, 6241, 4745, 9519,
         2553, 1786, 3274,  988, 1150,  250, 8562, 1376, 4501, 5233, 3899,
          352, 4601, 2717, 8635,  610, 8116, 2477,   48, 7837, 4374, 9950,
         2422, 3919, 4265, 3763, 9590, 5527, 4454, 6392, 2563, 3500, 8787,
         8795, 5297, 1486, 6379, 4973, 6816]),
  array([9527, 3059, 4654, 2769, 9546, 5557, 3330, 8392, 9079, 6066, 8794,
         6201, 6019, 9091, 3065, 5576, 4277, 1086, 9064, 5095, 8903, 2177,
         8505, 4707, 2201, 3518, 5102, 4363, 9748, 3677, 2286, 9341, 5752,
         7027, 9750,  487, 8515, 4814, 3985, 2882, 1649, 3103,  916, 4704,
          459, 9711, 4356, 6790, 1694, 2557]),
  array([ 0.41773133,  0.02838067,  0.51891014, ...,  0.68634368,
          0.90531818,  0.50229032]),
  array([ 0.07467551,  0.53234783,  0.21306196, ...,  0.71274754,
          0.30121287,  0.68003955])),
 (array([ 193, 7503, 1709,  896, 1500, 6355, 1767, 7910, 8855, 8392, 2652,
         6128, 7593, 285

In [82]:
tuple(foo[x][0] for x in range(len(foo)))

(array([3513, 7990, 6040, 3484, 8808, 4439, 5472, 6627, 6241, 4745, 9519,
        2553, 1786, 3274,  988, 1150,  250, 8562, 1376, 4501, 5233, 3899,
         352, 4601, 2717, 8635,  610, 8116, 2477,   48, 7837, 4374, 9950,
        2422, 3919, 4265, 3763, 9590, 5527, 4454, 6392, 2563, 3500, 8787,
        8795, 5297, 1486, 6379, 4973, 6816]),
 array([ 193, 7503, 1709,  896, 1500, 6355, 1767, 7910, 8855, 8392, 2652,
        6128, 7593, 2858, 7163, 9581, 6063,  186, 4081, 8053, 1589,  236,
        9571, 1905, 4103, 4673,   44, 9344, 4156, 1103, 7665, 1530, 7652,
        4320, 8012, 7597, 6516, 7759, 4790, 4256,  179, 7424, 7324, 1156,
        2135, 2291, 9915, 5094, 7702, 4802]),
 array([2306,  969, 7796,  405,  741, 9118, 6435, 7197, 8191, 6930, 5780,
         190, 3141, 9157, 8271, 8444, 3383, 8353, 1641, 3334, 2840, 5834,
        6727, 3034, 4620, 1171, 9707, 6059, 4777, 3060, 9708, 1909, 1909,
        7167, 2952, 5612, 3027, 8245, 2762, 7705, 7847, 6440, 9495, 9197,
         989,  589, 

In [76]:
%%timeit
item_bag = set()
for x in range(len(foo)):
    item_bag.update(foo[x][0])

47.3 µs ± 2.14 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [129]:
import uuid

In [152]:
foo = {}

In [154]:
foo['bar'] = 13

In [155]:
del foo['bar']

In [156]:
foo

{}

In [149]:
try:
    assert name
except:
    name = 'foo'

In [151]:
assert name

In [163]:
foo = str(uuid.uuid4())

In [164]:
bar = {}

In [165]:
bar[foo] = 12

In [166]:
bar

{'70ff005e-c317-43b5-b1c3-10b195c8e19f': 12}

In [171]:
keys, values = zip(*bar.items())

In [174]:
values

(12,)

In [175]:
import sched

In [177]:
s = sched.scheduler(time.time, time.sleep)

In [ ]:
s.enter()

In [118]:
sizeof.sizeof(foo[1][3])

8.0096e-05

In [158]:
start = time.time()
time.sleep(5)
end = time.time()

end-start

5.008731842041016

In [161]:
60*30

1800

In [119]:
import time

In [157]:
time.time()

1513560187.0112476

In [122]:
time.time()

1513556925.4130094

In [112]:
%%timeit
sim = np.array(tuple(foo[x][3][test] for x in range(len(foo))))

38.6 µs ± 2.38 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [117]:
np.sum(sim, axis=0).shape

(1000,)

In [114]:
sim.shape

(7, 1000)

In [15]:
sizeof.sizeof(test[0])

8.0096e-05

In [17]:
sizeof.getsizeof(row)

80096

In [28]:
del list

In [32]:
test = np.random.randint(0, 9999, 1000)

In [23]:
%%timeit
row[([1, 45, 57, 23, 1000, 240, 27, 500, ])]

2.39 µs ± 133 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [33]:
%%timeit
row[test]

2.95 µs ± 173 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [24]:
bar = np.zeros(10000)

In [102]:
test.shape

(1000,)

In [35]:
%%timeit
bar[test] = 1

4.39 µs ± 401 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [36]:
%%timeit
np.multiply(row, bar)

26.8 µs ± 1.44 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


Explored ideas of singleton pattern and Borg, but decided that just designing a module for Model is best. 

In [1]:
class Borg:
    __shared_state = {}
    def __init__(self):
        self.__dict__ = self.__shared_state

In [9]:
u_vec = np.zeros(10000)

In [16]:
class Foo():
    def __init__(self, arg):
        self.x = arg

In [24]:
test = Foo(1)

In [26]:
del test

In [11]:
liked = set([1, 3, 5])

In [31]:
liked.add(4)

In [27]:
bar = set([1, 3, 5])

In [33]:
liked.intersection_update

{4}

In [35]:
if bar.difference(liked):
    print('Foo')

In [30]:
if liked==bar

True

In [14]:
u_vec[list(liked)] = 1

In [15]:
u_vec[:10]

array([ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  0.])

In [2]:
test = Borg

In [3]:
test

__main__.Borg

In [4]:
Foo = Borg

In [5]:
print(Foo)

<class '__main__.Borg'>


In [7]:
Foo.__dict__

mappingproxy({'_Borg__shared_state': {},
              '__dict__': <attribute '__dict__' of 'Borg' objects>,
              '__doc__': None,
              '__init__': <function __main__.Borg.__init__>,
              '__module__': '__main__',
              '__weakref__': <attribute '__weakref__' of 'Borg' objects>})

In [7]:
Foo

In [5]:
Bar = Model('foo')

In [29]:
Bar.val

'foo'

In [2]:
%run lib/helper/load_rec_mats.py

In [3]:
%run lib/helper/load_search.py

In [6]:
from lib.recommend import get_sim
import numpy as np

In [5]:
class Recommender():
    
    def __init__(self, n_games=10000):
        self.u_vec = np.zeros(n_games)
        self.feat_bag = set()
        self.added_to_bag = set()
        self.liked = set()
        self.rated = set()
        self.item_bag = set()
        self.last_get = 0
        
    def rate(self, gs):
        self.u_vec[gs] = 1
        self.liked.add(gs)
        self.rated.add(gs)
        
    def get_bag(self, K=100):
        to_get = self.liked.difference(self.added_to_bag)
        while to_get:
            game = to_get.pop()
            top_feat_items, sim = get_sim.by_feats(game, K, feat_mat)
            self.feat_bag.update(top_feat_items)
            top_item_items, c_sim = get_sim.by_items(game, K, item_mat)
            self.item_bag.update(top_item_items)
            self.added_to_bag.add(game)
        
    def clean_bag(self):
        self.feat_bag.difference_update(self.rated)
        self.item_bag.difference_update(self.rated)
        exps = set(exp_mat[list(self.rated)].nonzero()[1])
        self.feat_bag.difference_update(exps)
        self.item_bag.difference_update(exps)
        
    def update_bag_vec(self):
        self.feat_bag_vec = np.zeros_like(self.u_vec)
        self.feat_bag_vec[list(self.feat_bag)] = 1
        self.item_bag_vec = np.zeros_like(self.u_vec)
        self.item_bag_vec[list(self.item_bag)] = 1
        
    def get_cum_vecs(self, item_weight=.7, feat_weight=.3):
        rated_sim_bag = np.multiply(item_mat[list(self.rated)], self.feat_bag_vec)
        cum_corr_vec = np.sum(rated_sim_bag, axis=0)
        self.bias_corr = np.multiply(cum_corr_vec, item_bias)
        rated_corr_bag = np.multiply(feat_mat[list(self.rated)], self.item_bag_vec)
        cum_sim_vec = np.sum(rated_corr_bag, axis=0)
        self.bias_sim = np.multiply(cum_sim_vec, item_bias)
        self.comb_vec = np.add(np.multiply(self.bias_corr, item_weight), np.multiply(self.bias_sim, feat_weight))
        
    def get(self, n):
        if len(self.rated) > self.last_get:
            self.get_bag()
            self.clean_bag()
            self.update_bag_vec()
            self.get_cum_vecs()
        comb_recs = np.argsort(self.comb_vec)[:-(n+1):-1]
        self.top_games = search_gname(comb_recs)
        _ = [print(game) for game in self.top_games]
        self.last_get = len(self.rated)

In [ ]:
def search_gname(gs_list):
    '''
    Return of list of gnames from list of gs.
    '''
    return [gname[gs] for gs in gs_list]

In [7]:
global feat_mat
global item_mat
global exp_mat
global gname

In [20]:
New_user = Recommender()

In [22]:
New_user.rate(gs['King of Tokyo'])

In [23]:
New_user.rate(gs['Agricola'])

In [24]:
New_user.rate(gs['Magic: The Gathering'])

In [25]:
New_user.get(50)

Masmorra de DADOS
In Flanders Field
Le Havre
Fields of Arle
Nusfjord
Pixel Tactics 4
Ninja Dice: Location Cards
Tomb Raider Collectible Card Game
Capo Dei Capi
Tiny Epic Galaxies Deluxe Edition
Food Chain
Summoner Wars: Phoenix Elves vs Tundra Orcs
Summoner Wars: Guild Dwarves vs Cave Goblins
Force of Will
Warhammer: Invasion
Risk Legacy
Star Wars: Destiny – Rey Starter Set
The Voyages of Marco Polo
Summoner Wars: Master Set
World of Warcraft Trading Card Game
Nations
Last Will
Belfort
Agricola: All Creatures Big and Small – More Buildings Big and Small
Pixel Tactics 2
Lewis & Clark
La Granja
Lords of War:  Elves versus Lizardmen
Machi Koro: Deluxe Edition
Suburbia
Cuba: El Presidente
Alien Frontiers
Dojo Kun
Viticulture: Arboriculture Expansion
Risk: Game of Thrones
Terraforming Mars
Las Vegas
Star Wars: Destiny – Kylo Ren Starter Set
Ashes: Rise of the Phoenixborn
Yamslam
Steam Park
At the Gates of Loyang
Mombasa
Viticulture Essential Edition
Tournay
Pixel Tactics 3
Würfel Bohnanza
H